puts "🌱 Seeding spices..."

# Seed your database here

#seed for students

student1 = Student.create(name:"John")
student2 = Student.create(name:"Sean")
student3 = Student.create(name:"Bron")
student4 = Student.create(name:"Don")
student5 = Student.create(name:"Steph")
student6 = Student.create(name:"Tasha")
student7 = Student.create(name:"Brent")
student8 = Student.create(name:"Wick")
student9 = Student.create(name:"Mickey")
student10 = Student.create(name:"Adele")



#seed for books

book1 = Book.create(book_title:"The Ecsape")
book2 = Book.create(book_title:"Mighty Man")
book3 = Book.create(book_title:"Theories of the Universe")
book4 = Book.create(book_title:"Silence of the Lamb")
book5 = Book.create(book_title:"Harry Potter")
book6 = Book.create(book_title:"The Dark Ferry")
book7 = Book.create(book_title:"Secrets of the Pyramids")
book8 = Book.create(book_title:"Astro && Prim")
book9 = Book.create(book_title:"Weekend Off")
book10 = Book.create(book_title:"Misguided Beats")
book11 = Book.create(book_title:"The Simbas && The Siberians")
book12 = Book.create(book_title:"Herucles Reborn")
book13 = Book.create(book_title:"The Stingy Rat")
book14 = Book.create(book_title:"Mr & Mrs Smith")
book15 = Book.create(book_title:"Bank Heist")
book16 = Book.create(book_title:"Pulp Fiction")
book17 = Book.create(book_title:"Tom & Jerry")
book18 = Book.create(book_title:"Trade Secrets")
book19 = Book.create(book_title:"Shadow Hunters")
book20 = Book.create(book_title:"The Great Beyond")
book21 = Book.create(book_title:"Cloud Atlas")
book22 = Book.create(book_title:"Pink Panther")
book23 = Book.create(book_title:"Physics 101")
book24 = Book.create(book_title:"Chemistry 101")
book25 = Book.create(book_title:"Biology 101")
book26 = Book.create(book_title:"Maths 101")
book27 = Book.create(book_title:"Pschology 101")
book28 = Book.create(book_title:"English 101")
book29 = Book.create(book_title:"The Great Recession")
book30 = Book.create(book_title:"Law && Order")
book31 = Book.create(book_title:"The ShawShank Redemption")
book32 = Book.create(book_title:"How to Survive in a Desert")
book33 = Book.create(book_title:"Aliens in the Attic")
book34 = Book.create(book_title:"Area 51 Leaks")

#seed for records

record1 = Record.create(book_author:"Phillip Monee",student_age:21 ,student_gender:"male",student_contact:0712345675 ,student_email:"Don@gmail.com",book_id:1,student_id:1)
record2 = Record.create(book_author:"John Meef",student_age:20 ,student_gender:"female",student_contact:0712345677 ,student_email:"ben@gmail.com",book_id:2,student_id:2)
record3 = Record.create(book_author:"Brandon Stark",student_age:18 ,student_gender:"male",student_contact:0712346675 ,student_email:"Dsem@gmail.com",book_id:3,student_id:3)
record4 = Record.create(book_author:"Sean Paul",student_age:23 ,student_gender:"male",student_contact:0712344675 ,student_email:"Dfdh@gmail.com",book_id:4,student_id:4)
record5 = Record.create(book_author:"Merf Ern",student_age:27 ,student_gender:"female",student_contact:0742345675 ,student_email:"Dnf@gmail.com",book_id:5,student_id:5)
record6 = Record.create(book_author:"PTeddy Ray",student_age:19 ,student_gender:"male",student_contact:0752345675 ,student_email:"fDon@gmail.com",book_id:6,student_id:6)
record7 = Record.create(book_author:"Sharon Wemp",student_age:20 ,student_gender:"male",student_contact:0722345675 ,student_email:"w21Don@gmail.com",book_id:7,student_id:7)
record8 = Record.create(book_author:"Sadi Sad",student_age:22 ,student_gender:"male",student_contact:0752345675 ,student_email:"Do43n@gmail.com",book_id:8,student_id:8)
record9 = Record.create(book_author:"Pitt Brad",student_age:24 ,student_gender:"female",student_contact:0716345675 ,student_email:"Do453n@gmail.com",book_id:9,student_id:9)
record10 = Record.create(book_author:"Oscar De La",student_age:16 ,student_gender:"female",student_contact:0717345675 ,student_email:"Do21n@gmail.com",book_id:10,student_id:10)
record11 = Record.create(book_author:"Canelo Alvarez",student_age:17 ,student_gender:"male",student_contact:0712345675 ,student_email:"D55on@gmail.com",book_id:11,student_id:11)
record12 = Record.create(book_author:"Miie Mii",student_age:24 ,student_gender:"female",student_contact:07123457675 ,student_email:"ppn@gmail.com",book_id:12,student_id:12)
# record13 = Record.create(book_author:"Uncle Phil",student_age:23 ,student_gender:"male",student_contact:0722386750 ,student_email:"Duui@gmail.com",book_id:13,student_id:13)
record14 = Record.create(book_author:"Halle Berry",student_age:22 ,student_gender:"female",student_contact:0712345675 ,student_email:"oip@gmail.com",book_id:14,student_id:14)
record15 = Record.create(book_author:"Night King",student_age:21 ,student_gender:"female",student_contact:07122345675 ,student_email:"Dgq7@gmail.com",book_id:15,student_id:15)
record16 = Record.create(book_author:"Rob Targaryen",student_age:18 ,student_gender:"male",student_contact:07152345675 ,student_email:"D126gs@gmail.com",book_id:16,student_id:16)
record17 = Record.create(book_author:"Jon Snow",student_age:19 ,student_gender:"female",student_contact:07123456675 ,student_email:"1g21@gmail.com",book_id:17,student_id:17)
record18 = Record.create(book_author:"Ser Davos",student_age:20 ,student_gender:"male",student_contact:07123456575 ,student_email:"1wq@gmail.com",book_id:18,student_id:18)
record19 = Record.create(book_author:"Optimus Prime",student_age:26 ,student_gender:"male",student_contact:071232645675 ,student_email:"fdsn@gmail.com",book_id:19,student_id:19)
record20 = Record.create(book_author:"Bumble Bee",student_age:25 ,student_gender:"female",student_contact:07123455675 ,student_email:"Do23322n@gmail.com",book_id:20,student_id:20)
record21 = Record.create(book_author:"Titanic Meek",student_age:22 ,student_gender:"male",student_contact:07123456755 ,student_email:"Dosdsdshdn@gmail.com",book_id:21,student_id:21)
record22 = Record.create(book_author:"Susan jim",student_age:17 ,student_gender:"female",student_contact:07123456755 ,student_email:"nnm@gmail.com",book_id:22,student_id:22)
record23 = Record.create(book_author:"Robert seem",student_age:24 ,student_gender:"male",student_contact:07123456375 ,student_email:"Dccc@gmail.com",book_id:23,student_id:23)
record24 = Record.create(book_author:"Justie leak",student_age:19 ,student_gender:"female",student_contact:071234522675 ,student_email:"csda@gmail.com",book_id:24,student_id:24)
record25 = Record.create(book_author:"Damp Damp",student_age:17 ,student_gender:"female",student_contact:07123456753 ,student_email:"aafa@gmail.com",book_id:25,student_id:25)
record26 = Record.create(book_author:"Orange Fruit",student_age:22 ,student_gender:"male",student_contact:07123456725 ,student_email:"avaa@gmail.com",book_id:26,student_id:26)
record27 = Record.create(book_author:"Billy One",student_age:19 ,student_gender:"female",student_contact:07123456754,student_email:"Donaaafagcx@gmail.com",book_id:27,student_id:27)
record28 = Record.create(book_author:"Chicken Broth",student_age:20 ,student_gender:"male",student_contact:07123456575 ,student_email:"gjvbdt@gmail.com",book_id:28,student_id:28)
record29 = Record.create(book_author:"Clark Kent",student_age:18 ,student_gender:"female",student_contact:07123456755 ,student_email:"xzzu@gmail.com",book_id:29,student_id:29)
record30 = Record.create(book_author:"Bron Sean",student_age:23 ,student_gender:"female",student_contact:071234567556 ,student_email:"xbxm@gmail.com",book_id:30,student_id:30)

puts "✅ Done seeding!"
